let auricularCloud = { id: '7', nombre: 'Auriculares gamer HyperX Cloud Alpha black y red', categoria: 3,
precio: 12252, stock: 8, cuotas: 12, interes: 0, envioGratis: true, esOferta: false, imagen:"auricular1.jpg" }
const productos = [
    { id: '1', nombre: 'Monitor Samsung Led 22 Pulgadas Frecuencia Hz 60 Hdmi Full Hd Promo', categoria: 1,
    precio: 26599, stock: 70, cuotas: 12, interes: 15, envioGratis: false, esOferta: false, imagen:"monitor22.jpg" },
    {id: '2', nombre: 'Monitor Led 24 Pulgadas Iqual Iq24h 1080p Hdmi Full Hd', categoria: 1,
    precio: 20999, stock: 40, cuotas: 12, interes: 0, envioGratis: false, esOferta: false, imagen:"monitor24.jpg" },
    {id: '3', nombre: 'Monitor LG 19M37A led 19 Pulgadas negro 100V/240V', categoria: 1,
    precio: 21839, stock: 5, cuotas: 12, interes: 15, envioGratis: false, esOferta: true, imagen:"monitor19.jpg" },
    { id: '4', nombre: 'Teclado Dell KB522 QWERTY inglés internacional color negro', categoria: 2,
    precio: 15707, stock: 2, cuotas: 0, interes: 0, envioGratis: true, esOferta: false, imagen:"teclado1.jpg"},
    { id: '5', nombre: 'Teclado gamer Redragon Vata Pro K580RGB-PRO QWERTY Outemu Brown español latinoamérica color negro con luz RGB', categoria: 2,
    precio: 7390, stock: 2, cuotas: 0, interes: 0, envioGratis: true, esOferta: false, imagen:"teclado2.jpg"  },
    { id: '6', nombre: 'Teclado gamer Redragon Brahma K586-PRO QWERTY Outemu Blue inglés US color negro con luz RGB', categoria: 2,
    precio: 10258, stock: 2, cuotas: 12, interes: 0, envioGratis: true, esOferta: false, imagen:"teclado3.jpg" },
    auricularCloud,
    { id: '8', nombre: 'Auriculares gamer inalámbricos Logitech G Series G935 negro y azul con luz rgb LED', categoria: 3,
    precio: 18999, stock: 4, cuotas: 12, interes: 0, envioGratis: true, esOferta: false, imagen:"auricular2.jpg" },
    { id: '9', nombre: 'Auriculares gamer inalámbricos Astro A50 negro y gris', categoria: 3,
    precio: 30291, stock: 10, cuotas: 12, interes: 0, envioGratis: true, esOferta: false, imagen:"auricular3.jpg" },
    { id: '10', nombre: 'Mouse de juego Redragon Centrophorus2 M601-RGB', categoria: 4,
    precio: 1739, stock: 12, cuotas: 12, interes: 0, envioGratis: true, esOferta: false, imagen:"mouse1.jpg" },
    { id: '11', nombre: 'Mouse de juego Logitech G Series Lightsync G203 black', categoria: 4,
    precio: 2549, stock: 12, cuotas: 12, interes: 10, envioGratis: true, esOferta: false, imagen:"mouse2.jpg" },
    { id: '12', nombre: 'Pendrive SanDisk Cruzer Blade 64GB 2.0 negro y rojo', categoria: 5,
    precio: 1061, stock: 20, cuotas: 0, interes: 0, envioGratis: true, esOferta: false, imagen:"pendrive1.jpg" },
    { id: '13', nombre: 'Gabinete Gamer Iqual Cm-9527 Leg Rgb Templado + Fuente', categoria: 6,
    precio: 7199, stock: 2, cuotas: 12, interes: 0, envioGratis: true, esOferta: false, imagen:"gabinete1.jpg" },
    { id: '14', nombre: 'Gabinete Gamer Noga 8608 Coolers Panel Vidrio + Fuente', categoria: 6,
    precio: 8499, stock: 2, cuotas: 0, interes: 0, envioGratis: true, esOferta: false, imagen:"gabinete2.jpg" },
    { id: '15', nombre: 'Gabinete Gamer Iqual Cm-2801 Templado Fuente 700w Led Cuotas', categoria: 6,
    precio: 10799, stock: 2, cuotas: 6, interes: 0, envioGratis: true, esOferta: false, imagen:"gabinete3.jpg" },
    { id: '16', nombre: 'Fuente de alimentación para PC Noga ATX-550 P4 550W negra 200V', categoria: 7,
    precio: 1429, stock: 2, cuotas: 0, interes: 0, envioGratis: true, esOferta: false, imagen:"fuente1.jpg" },
    { id: '17', nombre: 'Fuente de alimentación para PC Noga RGB Power ATX-700 RGB 700W negra 200V - 240V', 
    precio: 5529, stock: 2, cuotas: 12, interes: 10, envioGratis: true, esOferta: false, imagen:"fuente2.jpg" },
    { id: '18', nombre: 'Fuente de alimentación para PC Thermaltake Technology TR2 Series TR2-500NL2NC 500W black 115V/230V', categoria: 7,
    precio: 8199, stock: 2, cuotas: 12, interes: 0, envioGratis: true, esOferta: false, imagen:"fuente3.jpg" },
    { id: '19', nombre: 'Disco duro externo Western Digital WD Elements WDBUZG0010BBK 1TB negro', categoria: 8,
    precio: 6799, stock: 2, cuotas: 12, interes: 0, envioGratis: true, esOferta: false, imagen:"memoriaexterna1.jpg" },
    { id: '20', nombre: 'Disco duro externo Seagate Expansion STEA2000400 2TB negro', categoria: 8,
    precio: 9929, stock: 2, cuotas: 12, interes: 0, envioGratis: true, esOferta: false, imagen:"memoriaexterna2.jpg" },
    { id: '21', nombre: 'Disco duro externo Seagate Basic STJL2000400 2TB negro', categoria: 8,
    precio: 8899, stock: 2, cuotas: 12, interes: 0, envioGratis: true, esOferta: false, imagen:"memoriaexterna3.jpg" },
    { ...auricularCloud, id: '22', nombre: 'Auriculares gamer HyperX Cloud Alpha Violeta', imagen:"auricular4.jpg"}
]

module.exports = {
    productos,
  }
